import {
  ArrowForwardIos,
  ArrowForwardIosRounded,
  ArrowBackIosNew,
  ArrowBackIosRounded,
  MenuRounded,
  CloseRounded,
  Instagram,
  WifiRounded,
  LocalLaundryServiceRounded,
  BedRounded,
  SingleBedRounded,
  ChairRounded,
  MapRounded,
  MailRounded,
  PhoneRounded,
  BedroomChildRounded,
  LivingRounded,
  SingleBed,
  Living,
  Chair,
  ChairOutlined,
} from "@mui/icons-material";

export const IconsList = {
  ArrowForwardIos,
  ArrowForwardIosRounded,
  ArrowBackIosNew,
  ArrowBackIosRounded,
  MenuRounded,
  CloseRounded,
  Instagram,
  MailRounded,
  MapRounded,
  PhoneRounded,
  WifiRounded,
  BedRounded,
  SingleBedRounded,
  ChairRounded,
  LocalLaundryServiceRounded,
  Sofa: ChairOutlined,
  DoubleBed: BedRounded,
  SingleBed: SingleBed,
};
