import {
  ArrowForwardIos,
  ArrowForwardIosRounded,
  ArrowBackIosNew,
  ArrowBackIosRounded,
  MenuRounded,
  CloseRounded,
  Instagram,
  WifiRounded,
  LocalLaundryServiceRounded,
  BedRounded,
  MapRounded,
  MailRounded,
  PhoneRounded,
} from "@mui/icons-material";

export const IconsList = {
  ArrowForwardIos,
  ArrowForwardIosRounded,
  ArrowBackIosNew,
  ArrowBackIosRounded,
  MenuRounded,
  CloseRounded,
  Instagram,
  MailRounded,
  MapRounded,
  PhoneRounded,
  WifiRounded,
  BedRounded,
  LocalLaundryServiceRounded,
};
